"""initial

Revision ID: 4b951bfe6152
Revises: 276efb3740e0
Create Date: 2024-10-23 21:09:32.247143

"""
from alembic import op
import sqlalchemy as sa

from project.core.config import settings


# revision identifiers, used by Alembic.
revision = '4b951bfe6152'
down_revision = '276efb3740e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surname', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('name', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('patronymic', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('type_of_document', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('document', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('date_of_reg', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=True),
    sa.Column('phone', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document', 'type_of_document'),
    schema='hotels_schema'
    )
    op.drop_table('users', schema='hotels_schema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    schema='hotels_schema'
    )
    op.drop_table('clients', schema='hotels_schema')
    # ### end Alembic commands ###
