"""create clients

Revision ID: 5c4905d2016a
Revises: bda7641ae997
Create Date: 2024-11-07 09:18:08.440904

"""
from alembic import op
import sqlalchemy as sa

from project.core.config import settings


# revision identifiers, used by Alembic.
revision = '5c4905d2016a'
down_revision = 'bda7641ae997'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surname', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('name', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('patronymic', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('type_of_document', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('document', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('date_of_reg', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=True),
    sa.Column('phone', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document', 'type_of_document'),
    schema=settings.POSTGRES_SCHEMA
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients', schema='hotels_schema')
    # ### end Alembic commands ###
