"""clients - rename constraints

Revision ID: 6a138b6337e8
Revises: e3ffcc6f793b
Create Date: 2024-11-20 22:46:57.177429

"""
from alembic import op
import sqlalchemy as sa

from project.core.config import settings


# revision identifiers, used by Alembic.
revision = '6a138b6337e8'
down_revision = 'e3ffcc6f793b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('clients_document_type_of_document_key', 'clients', schema='hotels_schema', type_='unique')
    op.drop_constraint('clients_email_key', 'clients', schema='hotels_schema', type_='unique')
    op.create_unique_constraint('unique_document', 'clients', ['document', 'type_of_document'], schema='hotels_schema')
    op.create_unique_constraint('unique_email', 'clients', ['email'], schema='hotels_schema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_email', 'clients', schema='hotels_schema', type_='unique')
    op.drop_constraint('unique_document', 'clients', schema='hotels_schema', type_='unique')
    op.create_unique_constraint('clients_email_key', 'clients', ['email'], schema='hotels_schema')
    op.create_unique_constraint('clients_document_type_of_document_key', 'clients', ['document', 'type_of_document'], schema='hotels_schema')
    # ### end Alembic commands ###
