"""empty migration

Revision ID: 81c846528e06
Revises: 6167483d5d2f
Create Date: 2024-12-03 13:42:30.505410

"""
from alembic import op
import sqlalchemy as sa

from project.core.config import settings


# revision identifiers, used by Alembic.
revision = '81c846528e06'
down_revision = '6167483d5d2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
