"""initial

Revision ID: ad04e404faa9
Revises: 4b951bfe6152
Create Date: 2024-10-23 21:15:05.938543

"""
from alembic import op
import sqlalchemy as sa

from project.core.config import settings


# revision identifiers, used by Alembic.
revision = 'ad04e404faa9'
down_revision = '4b951bfe6152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
