"""hotels - rename constraints

Revision ID: b5d2b1e126ea
Revises: 6a138b6337e8
Create Date: 2024-11-20 23:38:00.286310

"""
from alembic import op
import sqlalchemy as sa

from project.core.config import settings


# revision identifiers, used by Alembic.
revision = 'b5d2b1e126ea'
down_revision = '6a138b6337e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('hotels_name_key', 'hotels', schema='hotels_schema', type_='unique')
    op.create_unique_constraint('unique_name', 'hotels', ['name'], schema='hotels_schema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_name', 'hotels', schema='hotels_schema', type_='unique')
    op.create_unique_constraint('hotels_name_key', 'hotels', ['name'], schema='hotels_schema')
    # ### end Alembic commands ###
