"""clients.email set nullable false, unique

Revision ID: c9a77edf9f86
Revises: fe791328188d
Create Date: 2024-11-20 20:15:15.556266

"""
from alembic import op
import sqlalchemy as sa

from project.core.config import settings


# revision identifiers, used by Alembic.
revision = 'c9a77edf9f86'
down_revision = 'fe791328188d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               schema=settings.POSTGRES_SCHEMA)
    op.create_unique_constraint(None, 'clients', ['email'], schema=settings.POSTGRES_SCHEMA)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', schema=settings.POSTGRES_SCHEMA, type_='unique')
    op.alter_column('clients', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               schema=settings.POSTGRES_SCHEMA)
    # ### end Alembic commands ###
