"""clients.date_of_reg add default value

Revision ID: e3ffcc6f793b
Revises: c9a77edf9f86
Create Date: 2024-11-20 21:22:07.174886

"""
from alembic import op
import sqlalchemy as sa

from project.core.config import settings


# revision identifiers, used by Alembic.
revision = 'e3ffcc6f793b'
down_revision = 'c9a77edf9f86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
